name: gencon
recipe: drupal8
config:
  php: '8.2'
  via: 'nginx'
  webroot: './web'
  database: 'mysql:5.7'
  xdebug: true
  config:
    php: lando.php.ini
services:
  appserver:
    build:
      - composer install
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://gencon.lndo.site"
  pma:
    type: phpmyadmin
